### ISSUE TITLE
Testnet Joe? 

### ISSUE THREAD

**Issue by jhb10c** [traderjoe-xyz/joe-core#6]
What are the addresses for Factory and router on the fuji testnet? I am unable to find the addresses for these contracts.

**Comment by cryptofish7** [comment]
We we're not on Fuji. Instead we're on Rinkeby:

JoeFactory: 0x86f83be9770894d8e46301b12E88e14AdC6cdb5F
JoeRouter02: 0x7E2528476b14507f003aE9D123334977F5Ad7B14
