### ISSUE TITLE
Use Constants for Precision

### ISSUE THREAD

**Issue by 0xm3rlin** [traderjoe-xyz/joe-core#67]
E.g. at https://github.com/traderjoe-xyz/joe-core/blob/5802b83ecd2df5f586650028bfcf43049899da20/contracts/StableJoeStaking.sol#L59

Using a normal storage slot results in unnecessary reads that the user has to pay for.

**Comment by cryptofish7** [comment]
Thanks for pointing this out, will keep in mind for next upgrade.
